In [3]:
import lap
import numpy as np


from lapjv import lapjv


In [102]:

rows = np.random.randint(3, 10)
cols = np.random.randint(3, 10)

# Generate the random 2D array with values between 1 and 10
cost_matrix = np.random.uniform(1, 11, size=(rows, cols))


print(f"Random array of size {rows}x{cols}:")
print(cost_matrix)

Random array of size 8x8:
[[ 8.62924619  5.93566877  8.67824448  3.99831349  6.91971319  6.68783669
   1.93025297  3.65754311]
 [ 7.94967544  6.9657782   6.20802007  3.56648094  7.24058188  7.36654522
   3.64309208  4.98727952]
 [ 9.1250263   4.75974354  7.38704808  1.30169688 10.50904876  1.85194868
   5.40222003  5.62307325]
 [ 7.0724897   7.73029221  6.65055547  9.89768349  1.47147634  9.90238704
   6.80431889  8.6355886 ]
 [ 5.46136928  4.00887878  4.28677693  8.97948207  3.59502374  1.53378407
   7.20149985  2.58006091]
 [ 7.84651303 10.57031938  6.31644816  4.80807659  1.19559282  5.45560073
   2.37025263  8.35041271]
 [10.07944268  6.18554658  4.82078245  8.30245272  8.54102519  9.75954833
   4.00360671  3.43396499]
 [ 8.43876112  6.21154306  8.15795765  4.91383524 10.33070606  9.11178066
   2.60006268  4.85284604]]


In [90]:

cost_limit=3

cost, x, y = lap.lapjv(cost_matrix, extend_cost=True, cost_limit=cost_limit)

print(x)
print(y)
print(cost)

[-1  1 -1  4  5  3 -1 -1 -1]
[-1  1 -1  5  3  4 -1]
6.47651150468303


In [81]:

n_rows = cost_matrix.shape[0]
n_cols = cost_matrix.shape[1]

n = n_rows + n_cols
cost_c_extended = np.empty((n, n), dtype=np.double)


cost_c_extended[:] = cost_limit / 2.


cost_c_extended[n_rows:, n_cols:] = 0
cost_c_extended[:n_rows, :n_cols] = cost_matrix
cost_c = cost_c_extended


x, y, _ = lapjv(cost_c_extended)

xf = np.where(x < n_cols, x, -1)[:n_rows]
yf = np.where(y < n_rows, y, -1)[:n_cols]

#print(cost)
print(xf)
print(yf)


real_cost = 0
for row_i , row in enumerate(cost_matrix):
    if xf[row_i] >= 0:
        real_cost += row[xf[row_i]]
print(real_cost)

[ 0  1 -1  2  4 -1]
[ 0  1  3 -1  4 -1]
9.488326300733242


# Pymatgen

In [51]:
from pymatgen.optimization.linear_assignment import LinearAssignment

In [85]:
x = LinearAssignment(cost_c_extended).solution
y = np.ones(len(x)) * -1
for i, j in enumerate(x):
    y[j] = i

xf = np.where(x < n_cols, x, -1)[:n_rows]
yf = np.where(y < n_rows, y, -1)[:n_cols]

#print(cost)
print(xf)
print(yf)


real_cost = 0
for row_i , row in enumerate(cost_matrix):
    if xf[row_i] >= 0:
        real_cost += row[xf[row_i]]


print(real_cost)

[ 0  1 -1  2  4 -1]
[ 0.  1.  3. -1.  4. -1.]
9.488326300733242


# Scipy

In [41]:
from scipy.optimize import linear_sum_assignment

In [113]:
cost_matrix = np.array([[1,2,3,4],[6,5,4,3]])

In [115]:
cost_limit=3

cost, x, y = lap.lapjv(cost_matrix, extend_cost=True, cost_limit=cost_limit)

print(x)
print(y)
print(cost)

[ 0 -1]
[ 0 -1 -1 -1]
1.0


In [116]:
n_rows = cost_matrix.shape[0]
n_cols = cost_matrix.shape[1]

n = n_rows + n_cols
cost_c_extended = np.empty((n, n), dtype=np.double)


cost_c_extended[:] = cost_limit / 2.


cost_c_extended[n_rows:, n_cols:] = 0
cost_c_extended[:n_rows, :n_cols] = cost_matrix


_, x = linear_sum_assignment(cost_c_extended)
y = np.ones(len(x)) * -1
for i, j in enumerate(x):
    y[j] = i
xf = np.where(x < n_cols, x, -1)[:n_rows]
yf = np.where(y < n_rows, y, -1)[:n_cols]

#print(cost)
print(xf)
print(yf)


real_cost = 0
for row_i , row in enumerate(cost_matrix):
    if xf[row_i] >= 0:
        real_cost += row[xf[row_i]]


print(real_cost)

[ 0 -1]
[ 0. -1. -1. -1.]
1


In [120]:
x
y_fake

array([0, 1, 2, 3, 4, 5], dtype=int64)